name: shine
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - torchmetrics
  - pip
  - pip:
      - absl-py==2.0.0
      - annotated-types==0.7.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - backcall==0.2.0
      - build==1.2.2.post1
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.8
      - cmake==3.27.5
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - executing==2.0.1
      - filelock==3.12.4
      - flatbuffers==23.5.26
      - fsspec==2023.9.2
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - h5py==3.10.0
      - huggingface-hub==0.17.3
      - idna==3.4
      - importlib-metadata==6.8.0
      - ipython==8.12.3
      - jedi==0.19.1
      - joblib==1.3.2
      - keras==2.13.1
      - libclang==16.0.6
      - lit==17.0.1
      - markdown==3.5.1
      - matplotlib-inline==0.1.6
      - numpy==1.24.4
      - oauthlib==3.2.2
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pip==25.0.1
      - pip-tools==7.4.1
      - pipdeptree==2.24.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pygments==2.16.1
      - pyproject-hooks==1.2.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.3.3
      - scikit-learn==1.3.1
      - scipy==1.10.1
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - six==1.16.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.12
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - timm==0.9.7
      - tomli==2.2.1
      - torchsampler==0.1.2
      - tqdm==4.66.1
      - traitlets==5.13.0
      - typing-extensions==4.13.2
      - tzdata==2023.3
      - urllib3==2.0.5
      - wandb==0.19.1
      - wcwidth==0.2.10
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - zipp==3.17.0
      - tensorboard
      - lion_pytorch